SuperDamp/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SuperDamp.Models
{
    public class Cart
    {
        
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key, Column(Order = 0)]
        public int Id { get; set; }
        [Column(Order = 1)]
        public string username { get; set; }
        [Column(Order = 2)]
        public int productId { get; set; }
        [Column(Order = 3)]
        public int quantity { get; set; }
        [NotMapped]
        public Product product { get; set; }
        [NotMapped]
        public bool isSelected { get; set; }

        public override string ToString()
        {
            string output = productId + "  " + isSelected;
            return output;
        }


    }
}

SuperDamp/Controllers/CartController.cs
using System;
using SuperDamp.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Database = SuperDamp.Models.Database;
using System.Threading.Tasks;
using System.Diagnostics;

namespace SuperDamp.Controllers
{
    public class CartController : Controller
    {
        Database db = new Database();
        // GET: Cart

        public ActionResult Index()
        {
            modelAdaptor ma = new modelAdaptor();
            string username = Session["username"].ToString();
            List<Cart> carts = db.carts.Where(u => u.username.Equals(username)).ToList();
            List<Product> products = db.Products.ToList();
            var list = (from c in carts
                        join p in products
                        on c.productId equals p.Id
                        select new Cart { quantity = c.quantity, product = p,productId=c.productId }).ToList();
            ma.carts = list;
            return View(ma);
        }


        public ActionResult add(int productId)
        {
            if(Session["username"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                addToCart(productId);
                return RedirectToAction("Index");
            }
            
        }

        [HttpPost]
        public ActionResult CartOperation(modelAdaptor ma,string operation)
        {
            if (ma.carts!=null)
            {
                string username = Session["username"].ToString();
                if (operation.Equals("delete"))
                {
                    var a = ma.carts.Where(s => s.isSelected == true).ToList();
                    foreach (var item in a)
                    {
                        Cart cart = new Cart();
                        cart = db.carts.Where(i => i.productId.Equals(item.productId)).Where(u => u.username.Equals(username)).FirstOrDefault();
                        db.carts.Remove(cart);
                        db.SaveChanges();
                    }

                    return RedirectToAction("Index");
                }
                else if (operation.Equals("checkOut"))
                {
                    modelAdaptor ma2 = new modelAdaptor();
                    var a = ma.carts.Where(s => s.isSelected == true).ToList();
                    List<Cart> cartInfo = new List<Cart>();
                    if (a.Count() > 0)
                    {
                        foreach (var item in a)
                        {
                            Cart cart = new Cart();
                            cart = db.carts.Where(i => i.productId.Equals(item.productId)).Where(u => u.username.Equals(username)).FirstOrDefault();
                            cartInfo.Add(cart);
                        }
                        var checkoutInfo = (from c in cartInfo
                                            join p in db.Products.ToList()
                                            on c.productId equals p.Id
                                            select new Cart { product = p, quantity = c.quantity }).ToList();
                        var shipInfo = db.UserInfos.Where(u => u.username.Equals(username)).ToList();
                        var payInfo = db.PaymentInfos.Where(u => u.username.Equals(username)).ToList();
                        ma2.carts = checkoutInfo;
                        ma2.userInfos = shipInfo;
                        ma2.paymentInfos = payInfo;
                        return View("checkOut", ma2);
                    }
                    else
                    {
                        ViewBag.blankCart = "Empty!";
                        return RedirectToAction("Index");
                    }
                }
                else if(operation.Equals("chooseMore"))
                {
                    return RedirectToAction("Index", "Product");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return RedirectToAction("Index");
            }


            
        }

        public ActionResult checkOut(modelAdaptor ma)
        {
            return View(ma);
        }


        public ActionResult createShipInfo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult createShipInfo(modelAdaptor ma)
        {
            UserInfo userInfo = new UserInfo();
            userInfo = ma.userInfo;
            userInfo.username = Session["username"].ToString();
            db.UserInfos.Add(userInfo);
            db.SaveChanges();
            return RedirectToAction("CheckOut");
        }
        public ActionResult createPaymentInfo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult createPaymentInfo(modelAdaptor ma,DateTime expireDate)
        {
            paymentInfo pi = new paymentInfo();
            pi = ma.paymentInfo;
            pi.username = Session["username"].ToString();
            pi.expireDate = expireDate;
            db.PaymentInfos.Add(pi);
            db.SaveChanges();
            return RedirectToAction("CheckOut");
        }

        public void addToCart(int productId)
        {
            Product product = db.Products.Where(i => i.Id.Equals(productId)).FirstOrDefault();
            Cart cart = new Cart();       
            cart.username = (string)Session["username"];
            cart.productId = product.Id;
            var cartQuery = db.carts.Where(u => u.username.Equals(cart.username) & u.productId.Equals(product.Id));
            if (cartQuery.Count() > 0)
            {
                cartQuery.FirstOrDefault().quantity += 1;
            }
            else
            {
                cart.quantity = 1;
                db.carts.Add(cart);
            }
            db.SaveChanges();            
        }



        public ActionResult Confirm()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Confirm(modelAdaptor ma,string userInfoSelect,string paymentInfo)
        {
            if (userInfoSelect != null && paymentInfo != null)
            {
                Order order = new Order();
                order.username = Session["username"].ToString();
                order.email = db.UserInfos.Where(e => e.username.Equals(order.username)).FirstOrDefault().email;
                order.shipmentInfo = userInfoSelect;
                order.paymentInfo = paymentInfo;
                order.orderStatus = "Processing";
                int amount = 0;
                string orderItems = "";
                var au = db.carts.Where(u => u.username.Equals(order.username)).ToList();
                var pu = db.Products.ToList();
                var bu = (from a in au
                          join p in pu
                          on a.productId equals p.Id
                          select new
                          {
                              name = p.Name,
                              quantity = a.quantity,
                              price = p.Price
                          }).ToList();
                foreach (var item in bu)
                {
                    orderItems += item.name + "*" + item.quantity + " ,";
                    amount += item.price * item.quantity;
                }
                order.orderItems = orderItems.Substring(0, orderItems.Length - 1) + " Amount: " + amount;
                order.orderTime = DateTime.Now;
                db.orders.Add(order);
                db.carts.RemoveRange(au);
                db.SaveChanges();
                return View();
            }
            else
            {
                ViewBag.checkout = "Please check required filed!";
                return RedirectToAction("CheckOut");
            }
            
        }
    }
}

SuperDamp/Views/Cart/CheckOut.cshtml
@model SuperDamp.Models.modelAdaptor

@{
    ViewBag.Title = "CheckOut";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="color:aqua;font-weight:bold;">CheckOut</h1>
@{ int total = 0;
    <h3>Your Order Details</h3>
    using (Html.BeginForm("Confirm", "Cart"))
    {
        <table class="table">
            @foreach (var item in Model.carts)
            {
                total += @item.product.Price * item.quantity;
                <tr>
                    <th>
                        <img src=@Html.DisplayFor(imgURL => item.product.imageURL) width="90px" height="90px" />
                        @Html.DisplayFor(name => item.product.Name)
                    </th>
                    <td>
                        $@Html.DisplayFor(price => item.product.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(quantity => item.quantity)
                    </td>
                </tr>
            }
        </table>
        <h2>Amount: $@total</h2>


        <br />
        <br />
        <h3>Shippment Information</h3>
        if (Model.userInfos.Count() > 0)
        {
            <select class="form-control" name="userInfoSelect">
                @foreach (var item in Model.userInfos)
                {
                    <option>@item.address, @item.province, @item.firstName, @item.mobilePhone</option>
                }

            </select>
        }
        <br />
        <a href="@Url.Action("createShipInfo", "Cart")">Add a new Shippment Information</a>
        <br/>
        <h3>Payment Information</h3>
        if (Model.paymentInfos.Count() > 0)
        {
            <select class="form-control" name="paymentInfo">
            @foreach (var item in Model.paymentInfos)
            {
                <option>@item.cardNo</option>
            }
            </select>
        }
        <br/><a href="@Url.Action("createPaymentInfo", "Cart")">Add a new Payment Information</a><br/><br/>
        <button type="submit" style="background-color:aqua">Confirm</button>
    }
}
<br/><button style="background-color:aqua" onclick="location.href='@Url.Action("Index","Cart")'">Cancle</button>
@if (ViewBag.checkout != null)
{
    <span style="color:red">@ViewBag.checkout</span>
}

SuperDamp/Views/Cart/Confirm.cshtml
@{
    ViewBag.Title = "Confirm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="color:greenyellow;align-content:center;margin-top:50px">Congrations! Your Order is being Processing.</h2>

SuperDamp/Views/Cart/Index.cshtml
@model SuperDamp.Models.modelAdaptor

@{ ViewBag.Title = "Index";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<h1 class="display-6" style="font-family: 'Orelega One', cursive; color: #f29672;">Checkout</h1>
<h2></h2>
@using (Html.BeginForm("CartOperation","Cart",FormMethod.Post))
{
<table class="table table-bordered" width="80%">
    <tr>
        <th>
            Select
        </th>
        <th>
            Product Name
        </th>
        <th>
            Price
        </th>
        <th>
            Quantity
        </th>
        <th>
            Total
        </th>
    </tr>
    @for (var i=0;i<Model.carts.Count();i++)
    {
        int total = Model.carts[i].product.Price * Model.carts[i].quantity;
<tr>
    <td>
        @Html.CheckBoxFor(m => m.carts[i].isSelected)
        @Html.HiddenFor(m => m.carts[i].productId)
        <img class="ml-2" src=@Html.DisplayFor(m => m.carts[i].product.imageURL) width="90px" height="110px" />
    </td>

    <td>
        @Html.DisplayFor(m => m.carts[i].product.Name)
    </td>
    <td>
        $@Html.DisplayFor(m => m.carts[i].product.Price)
    </td>
    <td>
        @Html.DisplayFor(m => m.carts[i].quantity)
    </td>
    <td>
        $ @total
    </td>
</tr>}
    @if (ViewBag.blankCart != null)
    {
<h3 style="color:red">@ViewBag.blankCart</h3>}
</table>
<div class="container">
  <div class="row">
      <div class="col-7">
          <div><button name="operation" class="btn btn-danger mt-3" type="submit" value="delete">Delete</button> </div>
      </div>
      <div class="col-3">
          <button style="margin-left:56%" name="operation" type="submit" class="btn btn-default" value="chooseMore">Choose More</button>

      </div>
      <div class="col-2">
          <button name="operation" class="btn btn-success" value="checkOut">CheckOut</button>

      </div>
  </div>
</div>
               }
<div style="margin-top:20px">
</div>

SuperDamp/Views/Cart/createPaymentInfo.cshtml
@model SuperDamp.Models.modelAdaptor

@{
    ViewBag.Title = "createPaymentInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>createPaymentInfo</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h4>paymentInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.paymentInfo.cardNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paymentInfo.cardNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paymentInfo.cardNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paymentInfo.expireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">               
                <input  type="date" name="expireDate"/>
                @Html.ValidationMessageFor(model => model.paymentInfo.expireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paymentInfo.cvv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paymentInfo.cvv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paymentInfo.cvv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CheckOut")
</div>

SuperDamp/Views/Cart/createShipInfo.cshtml
@model SuperDamp.Models.modelAdaptor
    @using SuperDamp.Models

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h4>UserInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.userInfo.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userInfo.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userInfo.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userInfo.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userInfo.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userInfo.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userInfo.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userInfo.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userInfo.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userInfo.mobilePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userInfo.mobilePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userInfo.mobilePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userInfo.gener, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userInfo.gener, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userInfo.gener, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userInfo.province, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userInfo.province, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userInfo.province, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userInfo.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userInfo.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userInfo.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userInfo.comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userInfo.comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userInfo.comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CheckOut")
</div>