SuperDamp/Controllers/HomeController.cs
using SuperDamp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperDamp.Controllers
{
    public class HomeController : Controller
    {
        public static List<Product> products = new List<Product>();

        public ActionResult Index()
        {

            return View();
        }

        public ActionResult Product()
        {
            return View();
        }

       

        public ActionResult Checkout(Product product)
        { 
          

            return View("Checkout", products);
        }



    }
}

SuperDamp/Controllers/ProductController.cs
using System;
using SuperDamp.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Database = SuperDamp.Models.Database;
using System.Threading.Tasks;
using System.Diagnostics;

namespace SuperDamp.Controllers
{
    public class ProductController : Controller
    {
        Database db = new Database();
        // GET: Product
        public ActionResult Index()
        {
            modelAdaptor modelAdaptor = new modelAdaptor();
            modelAdaptor.products = db.Products.ToList();
            return View(modelAdaptor);
        }

        public ActionResult Create()
        {
            if (Session["adminName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
        }
        [HttpPost]
        public ActionResult Create(Product product)
        {
            db.Products.Add(product);
            db.SaveChanges();
            return RedirectToAction("Admin_Product", "Admin");
        }


        public ActionResult Delete(int id)
        {
            if (Session["adminName"] != null)
            {
                Product product = db.Products.Where(i => i.Id.Equals(id)).FirstOrDefault();
                db.Products.Remove(product);
                db.SaveChanges();
                return RedirectToAction("Admin_Product", "Admin");
            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
        }

        public ActionResult Update(int id)
        {
            if (Session["adminName"] != null)
            {
                Product product = db.Products.Where(p => p.Id.Equals(id)).FirstOrDefault();
                return View(product);
            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
        }


        [HttpPost]
        public ActionResult Update(Product product)
        {
            Product product1 = db.Products.Where(i => i.Id.Equals(product.Id)).FirstOrDefault();
            product1.Name = product.Name;
            product1.Price = product.Price;
            product1.imageURL = product.imageURL;
            product1.Sex = product.Sex;
            product1.Category = product.Category;
            product1.Description = product.Description;
            db.SaveChanges();
            return RedirectToAction("Admin_Product", "Admin");
        }
    }
}

SuperDamp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Super Damp Home Page";
}

<div class="jumbotron text-center">
    <h1 class="display-3" style="font-family: 'Orelega One', cursive; color: #f29672;">Super Damp &copy;</h1>
    <p class="lead" style="font-family: 'Raleway', sans-serif; color: #f29672;">"You gotta have style. It helps you get down the stairs. It helps you get up in the morning. It’s a way of life. Without it, you’re nobody. I’m not talking about lots of clothes.”</p>
    <p><a onclick="location.href = '@Url.Action("Index","Product")'" class="btn btn-danger btn-lg">Check out our products!</a></p>
</div>

<div class="row">
    <div class="col-md-6">
        <img src="https://images.unsplash.com/photo-1445205170230-053b83016050?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8Y2xvdGhpbmd8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" />
    </div>
    <div class="col-md-6">
        <img src="https://images.unsplash.com/photo-1523381210434-271e8be1f52b?ixid=MXwxMjA3fDB8MHxzZWFyY2h8M3x8Y2xvdGhpbmd8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" />
    </div>    
</div>
<div class="row" style="margin-top:50px;">
    <div class="col-md-6">
        <img src="https://images.unsplash.com/photo-1544441893-675973e31985?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Y2xvdGhpbmd8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" />
    </div>
    <div class="col-md-6">
        <img src="https://images.unsplash.com/photo-1543087903-1ac2ec7aa8c5?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Nnx8Y2xvdGhpbmd8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" />
    </div>
</div>
<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
    <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
            <h2 class="display-5">Meet Our Celebrity !</h2>
            <img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/celebrities-with-great-personal-style-1529067614.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*" />
        </div>
    </div>
</div>