SuperDamp/Controllers/CareerController.cs
using System;
using SuperDamp.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Database = SuperDamp.Models.Database;
using System.Threading.Tasks;
using System.Diagnostics;

namespace SuperDamp.Controllers
{
    public class CareerController : Controller
    {
        // GET: Career
        Database db = new Database();
        // GET: career
        public ActionResult Index()
        {
            modelAdaptor modelAdaptor = new modelAdaptor();
            modelAdaptor.careers = db.Careers.ToList();
            return View(modelAdaptor);
        }


        public ActionResult Create()
        {
            if (Session["adminName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
           
        }

        [HttpPost]
        public ActionResult Create(modelAdaptor modelAdaptor)
        {
            db.Careers.Add(modelAdaptor.career);
            db.SaveChanges();

            return RedirectToAction("Admin_Career", "Admin");
        }

        public ActionResult Delete(int id)
        {
            Career career = db.Careers.Where(f => f.Id.Equals(id)).FirstOrDefault();
            db.Careers.Remove(career);
            db.SaveChanges();
            return RedirectToAction("Admin_Career","Admin");
        }

        public ActionResult Update(int id)
        {
            if (Session["adminName"] != null)
            {
                Career career = db.Careers.Where(f => f.Id.Equals(id)).FirstOrDefault();
                modelAdaptor modelAdaptor = new modelAdaptor();
                modelAdaptor.career = career;
                return View(modelAdaptor);
            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
            
        }
        [HttpPost]
        public ActionResult Update(modelAdaptor modelAdaptor)
        {

            var getcareer = db.Careers.FirstOrDefault(F => F.Id.Equals(modelAdaptor.career.Id));
            getcareer.jobTitle = modelAdaptor.career.jobTitle;
            getcareer.Type = modelAdaptor.career.Type;
            getcareer.Reference = modelAdaptor.career.Reference;
            getcareer.Location = modelAdaptor.career.Location;
            getcareer.Hours = modelAdaptor.career.Hours;
            getcareer.roleDescription = modelAdaptor.career.roleDescription;
            db.SaveChanges();
            return RedirectToAction("Admin_Career","Admin");
        }
        public async Task<int> SaveChangesAsync()
        {
            Task<int> task1 = db.SaveChangesAsync();
            try
            {
                await task1;
            }
            catch (Exception ex)
            {
                throw;
            }
            return task1.Result;
        }



    }
}

SuperDamp/Controllers/FAQController.cs
using System;
using SuperDamp.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Database = SuperDamp.Models.Database;
using System.Threading.Tasks;

namespace SuperDamp.Controllers
{
    public class FAQController : Controller
    {
        Database db = new Database();
        // GET: FAQ
        public ActionResult Index()
        {
            modelAdaptor modelAdaptor = new modelAdaptor();
            modelAdaptor.faqs = db.FAQs.ToList();
            return View(modelAdaptor);
        }


        public ActionResult Create()
        {
            if (Session["adminName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
        }

        [HttpPost]
        public ActionResult Create(modelAdaptor modelAdaptor)
        {
                db.FAQs.Add(modelAdaptor.faq);
                db.SaveChanges();
            
                return RedirectToAction("Admin_Faq","Admin");
        }

        public ActionResult Delete(int id)
        {
            FAQ faq = db.FAQs.Where(f => f.Id.Equals(id)).FirstOrDefault();
            db.FAQs.Remove(faq);
            db.SaveChanges();
            return RedirectToAction("Admin");
        }

        public ActionResult Update(int id)
        {
            if (Session["adminName"] != null)
            {
                FAQ faq = db.FAQs.Where(f => f.Id.Equals(id)).FirstOrDefault();
                modelAdaptor modelAdaptor = new modelAdaptor();
                modelAdaptor.faq = faq;
                return View(modelAdaptor);
            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
            
        }
        [HttpPost]
        public ActionResult Update(modelAdaptor modelAdaptor)
        {

           var getFaq = db.FAQs.FirstOrDefault(F => F.Id.Equals(modelAdaptor.faq.Id));
           getFaq.Question = modelAdaptor.faq.Question;
           getFaq.Answer = modelAdaptor.faq.Answer;
            db.SaveChanges();    
           return RedirectToAction("Admin");
        }
        public async Task<int> SaveChangesAsync()
        {
            Task<int> task1 = db.SaveChangesAsync();
            try
            {
                await task1;
            }
            catch (Exception ex)
            {
                throw;
            }
            return task1.Result;
        }


    }
}

SuperDamp/Views/Admin/Admin_Career.cshtml
@model SuperDamp.Models.modelAdaptor
@{ Layout = null; }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Orelega+One&family=Raleway:ital,wght@1,400;1,600&display=swap" rel="stylesheet">
</head>
<body class="bg-warning m-5" >

    <div class="jumbotron">
        <h1 class="display-3" style="font-family: 'Orelega One', cursive; color: #ff661a;">Admin Page for Careers</h1>

    </div>
    <div class="card">
        <img class="card-img"
             src="https://cdn.syncfusion.com/content/images/Careers/career-logo.png"
             alt="Card image">
        <div class="card-img-overlay">
            <h1 class="card-text font-weight-bolder">This is my caeer.</h1>
            <h1 class="card-text font-weight-bolder">This is my SuperDamp</h1>
        </div>
    </div>
    <span class="display-5 ml-1" style="font-family: 'Orelega One', cursive; color: #ff661a;">Create New Career HERE: </span><button class="btn btn-default p-1 m-4 text-white">@Html.ActionLink("Create", "Create", "Career")</button>
    <div class="container mt-3">
        @foreach (var obj in Model.careers)
        {
<div class="row">
    <div class="card">
        <div class="card-header">
            <span style="color: #fc5203;">Job Title:</span> @obj.jobTitle
        </div>
        <div class="card-body">
            <p class="card-text"><span style="color: #fc5203;">Type:</span> @obj.Type</p>
            <p class="card-text"><span style="color: #fc5203;">Reference:</span> @obj.Reference</p>
            <p class="card-text"><span style="color: #fc5203;">Hours:</span> @obj.Hours</p>
            <p class="card-text"><span style="color: #fc5203;">Location:</span> @obj.Location</p>
            <p class="card-text"><span style="color: #fc5203;">Role Description:</span> @obj.roleDescription</p>

        </div>
        <div class="card-footer">
            <a href="@Url.Action("Update","Career", new { id = obj.Id })" class="btn btn-danger mx-2 mb-1">Update</a>
            <a href="@Url.Action("Delete","Career", new { id = obj.Id })" class="btn btn-danger mx-2 mb-1">Delete</a>
        </div>
    </div>
</div>      }
    </div>

    <footer class="text-center  m-3">
        <span class="display-6 " style="font-family: 'Orelega One', cursive; color: #ff661a;">2021 SuperDamp</span>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

SuperDamp/Views/Admin/Admin_Faq.cshtml
@model SuperDamp.Models.modelAdaptor

@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="display-6 " style="font-family: 'Orelega One', cursive; color: #ff661a;">Admin For FAQ</h2>

<p>
    @Html.ActionLink("Create New", "Create","FAQ")
</p>
<table class="table">
    <tr>
        <th></th>
    </tr>

    @foreach (var obj in Model.faqs)
    {
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <p class="card-text">@Html.DisplayFor(model => obj.Question)</p>
                </div>
                <div class="card-body">
                    <p class="card-text">@Html.DisplayFor(model => obj.Answer)</p>
                </div>
                <div class="card-footer">

                    <a href="@Url.Action("Update","FAQ", new { id = obj.Id })" class="btn btn-danger mx-2 mb-1">Update</a>
                    <a href="@Url.Action("delete","FAQ", new { id = obj.Id })" class="btn btn-danger mx-2 mb-1">Delete</a>
                </div>
            </div>
        </div>




    }

</table>

SuperDamp/Views/Admin/Admin_Product.cshtml
@model  IEnumerable<SuperDamp.Models.Product>

@{
    ViewBag.Title = "Admin_Product";
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Orelega+One&family=Raleway:ital,wght@1,400;1,600&display=swap" rel="stylesheet">
</head>
<body class="bg-warning">

    <div class="jumbotron jumbotron-fluid">
        <div class="container text-center">
            <h1 class="display-4">Admin Page For PRODUCTS</h1>

        </div>
    </div>

    <div class="container">
        <div class="row display-5 " style="font-family: 'Orelega One', cursive; color: #ff661a;">
            Create a new product HERE: <a href="@Url.Action("create","Product")" class="btn btn-success mx-4 px-3 mb-4">Create</a>
        </div>
        <div class="row">
           
            @if (Model.Count() > 0)
            {

                foreach (var obj in Model)
                {
                    <div class="col-sm-3">
                        <div class="card mb-2">
                            <img style="width: 200px; height: 300px; margin-left: auto;margin-right: auto;" class="card-img-top img" src=@obj.imageURL alt="Card image cap">
                            <div class="card-body">
                                <h4 class="card-title">@obj.Name</h4>
                                <h6 class="card-subtitle mb-2 text-muted">@obj.Description</h6>
                                <p class="card-text">
                                    US $ @obj.Price
                                </p>
                            </div>
                            <div class="card-footer text-center">
                                <div class=" btn-group" role="group">
                                    <a href="@Url.Action("update","Product", new { id = obj.Id })" class="btn btn-success mx-2 mb-1">
                                        <i class="far fa-edit">&nbsp;<span class="text-monospace">Edit</span></i>
                                    </a>
                                    <a href="@Url.Action("delete","Product", new { id = obj.Id })" class="btn btn-danger mx-2 mb-1">
                                        <i class="far fa-edit">&nbsp;<span class="text-monospace">Delete</span></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
    <footer class="text-center m-3">
        <span class="display-6 " style="font-family: 'Orelega One', cursive; color: #ff661a;">2021 SuperDamp</span>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

SuperDamp/Views/Admin/Admin_order.cshtml
@model SuperDamp.Models.modelAdaptor
@{
    ViewBag.Title = "Admin_order";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin_order</h2>

<h2 class="display-6" style="font-family: 'Orelega One', cursive; color: #f29672;">My Order</h2>
@{ int i = 1;
    if (Model.orders != null)
    {
        foreach (var order in Model.orders)
        {
<table class="table table-striped">
    <tr>
        <td>Order @i</td>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(o => order.orderNo)
        </td>
        <td>
            @Html.DisplayFor(o => order.orderTime)
        </td>
        <td>
            @Html.DisplayFor(o => order.orderItems)
        </td>
        <td>
            @Html.DisplayFor(o => order.orderStatus)<br /><br />
            @if (order.orderStatus.Equals("Processing"))
            {
                <button class="btn btn-success" onclick="location.href = '@Url.Action("Ship", "User", new { id = order.orderNo })'">Ship</button><br /><br />
                <button class="btn btn-danger" onclick="location.href = '@Url.Action("Cancel2", "User", new { id = order.orderNo })'">Cancel</button>
            }

        </td>
    </tr>
    @{i++; }
</table> }

            }
            else
        {
<h2 style="font-weight:bold">No Order yet!</h2> } }

SuperDamp/Views/Admin/Index.cshtml
@model SuperDamp.Models.Admin

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Orelega+One&family=Raleway:ital,wght@1,400;1,600&display=swap" rel="stylesheet">
</head>
<body class="bg-warning">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4 class="display-6 ml-3 mt-2" style="font-family: 'Orelega One', cursive; color: #f29672;"><span class="mr-3 p-2 bg-danger text-white" style=" border-radius: 10px;">SuperDamp</span>Admin</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form class="bg-danger">
            <div class="form-group w-50">
                @Html.LabelFor(model => model.adminName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.adminName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.adminName, "", new { @class = "text-danger", @placeholder = "admin username" })
                </div>
            </div>
            <div class="form-group w-50">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger", @placeholder = "admin password" })
                    @if (ViewBag.adminLogin != null)
                    {
                        <h3 style="color:palevioletred">@ViewBag.adminLogin</h3>
                    }
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Login" class="btn btn-success" />
                </div>
            </div>
        </form>
        </div>
    }

    <div class="ml-3">
        @Html.ActionLink("Back to Home", "Index", "Home")
    </div>
    <footer class="text-center  m-3">
        <span class=" display-6 " style="font-family: 'Orelega One', cursive; color: #ff661a;">2021 SuperDamp</span>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

SuperDamp/Views/Admin/Logined.cshtml
@model SuperDamp.Models.Admin



@{
    ViewData["Title"] = "Admin Administration";
}
<h1>Admin Control Page</h1>

<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
    <div class="btn-group" role="group">
        <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Products
        </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <a class="nav-link text-dark" href="@Url.Action("Admin_product","Admin")">Product Administration</a>
        </div>
    </div>
    <div class="btn-group" role="group">
        <button id="btnGroupDrop2" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            FAQ
        </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <a class="nav-link text-dark" href="@Url.Action("Admin_Faq","Admin")">FAQ Adminstration</a>
        </div>
    </div>
    <div class="btn-group" role="group">
        <button id="btnGroupDrop2" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Career
        </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <a class="nav-link text-dark" href="@Url.Action("Admin_Career","Admin")">Career Administration</a>
        </div>
    </div>
    <div class="btn-group" role="group">
        <button id="btnGroupDrop2" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Messages
        </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <a class="nav-link text-dark" href="@Url.Action("Show_Message","Admin")">Show All</a>
        </div>
    </div>
    <div class="btn-group" role="group">
        <button id="btnGroupDrop2" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Orders
        </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <a class="nav-link text-dark" href="@Url.Action("Admin_order","Admin")">Order Administration</a>
        </div>
    </div>
</div>

SuperDamp/Views/Admin/Show_Message.cshtml
@model IEnumerable<SuperDamp.Models.Message>

@{
    ViewBag.Title = "Show_Message";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h2>Customer Feedbacks</h2>

</div>

<div class="container">
    @if (Model.Count()>0)
    {
        foreach (var obj in Model)
        {
            <div class="row">
                <div class="card w-100">
                    <div class="card-body">
                        <p class="card-text"><span style="color: #fc5203;">Name:</span> @obj.Name</p>
                        <p class="card-text"><span style="color: #fc5203;">Email:</span> @obj.Email</p>
                        <p class="card-text"><span style="color: #fc5203;">Phone Number:</span> @obj.phoneNumber</p>
                        <p class="card-text"><span style="color: #fc5203;">Message:</span> @obj.customerMessage</p>
                        <p class="card-text"><a href="@Url.Action("reply","message")">Reply</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="@Url.Action("delete","message")">Delete</a></p>

                    </div>
                </div>
            </div>
        }
    }
</div>